import type { SeoBlogPost } from "@/lib/db/seo-queries";

/**
 * Phase 32 — Website Blog Export.
 * Turns approved SEO Factory posts into TypeScript blog objects that drop
 * straight into the public PlantPal site's src/lib/blog/posts.ts.
 */

export interface WebsiteBlogPost {
  title: string;
  slug: string;
  metaDescription: string;
  date: string;
  author: string;
  category: string;
  tags: string[];
  featuredImage?: string;
  intro: string;
  sections: { subhead: string; body: string }[];
  faqs: { question: string; answer: string }[];
}

/** Map a Marketing OS post onto the public site's blog shape. */
export function buildWebsiteBlogObject(post: SeoBlogPost): WebsiteBlogPost {
  return {
    title: post.headline || post.seoTitle || post.keyword,
    slug: post.slug,
    metaDescription: post.metaDescription,
    date: (post.publishedAt ?? post.createdAt).slice(0, 10),
    author: post.author || "PlantPal Team",
    category: post.category || "Plant Care",
    tags: post.tags.length > 0 ? post.tags : [post.keyword].filter(Boolean),
    ...(post.featuredImage ? { featuredImage: post.featuredImage } : {}),
    intro: post.intro,
    sections: post.sections,
    faqs: post.faq,
  };
}

/** Escape a string for a single-quoted TS literal. */
function ts(value: string): string {
  return `'${value.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\r?\n/g, "\\n")}'`;
}

/** Render the post as a TypeScript object literal ready to paste into posts.ts. */
export function renderTsSnippet(obj: WebsiteBlogPost): string {
  const lines: string[] = [];
  lines.push("{");
  lines.push(`  title: ${ts(obj.title)},`);
  lines.push(`  slug: ${ts(obj.slug)},`);
  lines.push(`  metaDescription: ${ts(obj.metaDescription)},`);
  lines.push(`  date: ${ts(obj.date)},`);
  lines.push(`  author: ${ts(obj.author)},`);
  lines.push(`  category: ${ts(obj.category)},`);
  lines.push(`  tags: [${obj.tags.map(ts).join(", ")}],`);
  if (obj.featuredImage) {
    lines.push(`  featuredImage: ${ts(obj.featuredImage)},`);
  }
  lines.push(`  intro: ${ts(obj.intro)},`);
  lines.push("  sections: [");
  for (const s of obj.sections) {
    lines.push("    {");
    lines.push(`      subhead: ${ts(s.subhead)},`);
    lines.push(`      body: ${ts(s.body)},`);
    lines.push("    },");
  }
  lines.push("  ],");
  lines.push("  faqs: [");
  for (const f of obj.faqs) {
    lines.push("    {");
    lines.push(`      question: ${ts(f.question)},`);
    lines.push(`      answer: ${ts(f.answer)},`);
    lines.push("    },");
  }
  lines.push("  ],");
  lines.push("},");
  return lines.join("\n");
}

/** Full .ts file content for the download button. */
export function renderTsFileSnippet(obj: WebsiteBlogPost): string {
  return [
    `// PlantPal blog post: ${obj.title}`,
    `// Generated by Marketing OS SEO Factory on ${new Date().toISOString().slice(0, 10)}`,
    `// Paste this object into the posts array in src/lib/blog/posts.ts`,
    "",
    renderTsSnippet(obj),
    "",
  ].join("\n");
}

// ---------------------------------------------------------------------------
// SEO quality checks — runs against the post before export
// ---------------------------------------------------------------------------

export interface ExportQualityCheck {
  label: string;
  passed: boolean;
  detail: string;
}

export interface ExportQualityResult {
  passed: boolean;
  score: number;
  checks: ExportQualityCheck[];
}

const AI_TELLS = [
  "delve",
  "furthermore",
  "moreover",
  "in conclusion",
  "in this article",
  "it is important to note",
  "when it comes to",
  "a wide range of",
  "embark on",
  "unlock the secrets",
  "elevate your",
  "game-changer",
  "dive into",
  "let's explore",
  "in the world of",
];

const FLAT_TONE_OPENERS = [
  "plants are a great way to",
  "proper",
  "it is essential",
  "it's essential to",
  "houseplants have become increasingly popular",
  "gardening is a rewarding hobby",
];

function words(text: string): number {
  return text.split(/\s+/).filter(Boolean).length;
}

export function checkExportQuality(post: SeoBlogPost): ExportQualityResult {
  const fullText = [
    post.headline,
    post.intro,
    ...post.sections.flatMap((s) => [s.subhead, s.body]),
    ...post.faq.flatMap((f) => [f.question, f.answer]),
    post.cta,
  ].join("\n");
  const lower = fullText.toLowerCase();

  const checks: ExportQualityCheck[] = [];

  // 1. No em dashes
  const hasEmDash = fullText.includes("—") || /\w--\w/.test(fullText);
  checks.push({
    label: "No em dashes",
    passed: !hasEmDash,
    detail: hasEmDash ? "Em dashes found. Replace with periods or commas." : "Clean.",
  });

  // 2. Short sentences
  const sentences = fullText.split(/[.!?]+/).filter((s) => s.trim().length > 0);
  const longOnes = sentences.filter((s) => words(s) > 28).length;
  const shortOk = sentences.length === 0 || longOnes / sentences.length <= 0.25;
  checks.push({
    label: "Short sentences",
    passed: shortOk,
    detail: shortOk ? "Punchy." : `${longOnes} sentences run past 28 words. Chop them.`,
  });

  // 3. No generic AI language
  const aiHits = AI_TELLS.filter((p) => lower.includes(p));
  checks.push({
    label: "No generic AI language",
    passed: aiHits.length === 0,
    detail: aiHits.length === 0 ? "No AI tells." : `Found: ${aiHits.slice(0, 3).join("; ")}`,
  });

  // 4. Funny and direct tone — heuristic: short intro sentences, no flat openers,
  // at least some second-person address
  const flatHits = FLAT_TONE_OPENERS.filter((p) => post.intro.toLowerCase().startsWith(p) || lower.includes(p));
  const speaksToReader = /\byour?\b/i.test(fullText);
  const toneOk = flatHits.length === 0 && speaksToReader;
  checks.push({
    label: "Funny and direct tone",
    passed: toneOk,
    detail: toneOk
      ? "Talks to the reader, no lecture energy."
      : flatHits.length > 0
        ? `Flat phrasing detected: "${flatHits[0]}". Your plant is not a textbook.`
        : "Never addresses the reader. Use 'you' and 'your plant'.",
  });

  // 5. Helpful answer fast — the intro should get to the point quickly
  const introWords = words(post.intro);
  const fastAnswer = introWords > 0 && introWords <= 80;
  checks.push({
    label: "Helpful answer fast",
    passed: fastAnswer,
    detail: fastAnswer
      ? `Intro is ${introWords} words. Straight to the point.`
      : introWords === 0
        ? "No intro."
        : `Intro is ${introWords} words. Answer in the first 80 or lose them.`,
  });

  // 6. Includes FAQ
  checks.push({
    label: "Includes FAQ",
    passed: post.faq.length >= 2,
    detail: post.faq.length >= 2 ? `${post.faq.length} FAQs.` : "Needs at least 2 FAQs for the schema payoff.",
  });

  // 7. Includes CTA
  const hasCta = post.cta.trim().length > 10;
  checks.push({
    label: "Includes CTA",
    passed: hasCta,
    detail: hasCta ? "CTA present." : "No CTA. Every post sells PlantPal once.",
  });

  // 8. Has internal links
  checks.push({
    label: "Has internal links",
    passed: post.internalLinks.length >= 1,
    detail:
      post.internalLinks.length >= 1
        ? `${post.internalLinks.length} internal links.`
        : "Zero internal links. Add at least one.",
  });

  // 9. Meta description under 160 chars
  const metaLen = post.metaDescription.length;
  const metaOk = metaLen > 0 && metaLen <= 160;
  checks.push({
    label: "Meta description under 160 chars",
    passed: metaOk,
    detail: metaOk ? `${metaLen}/160 chars.` : metaLen === 0 ? "Missing meta description." : `${metaLen} chars. Google cuts it at 160.`,
  });

  // 10. Slug is clean
  const slugOk = /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(post.slug);
  checks.push({
    label: "Slug is clean",
    passed: slugOk,
    detail: slugOk ? `/blog/${post.slug}` : `"${post.slug}" — lowercase letters, numbers, and hyphens only.`,
  });

  const passedCount = checks.filter((c) => c.passed).length;
  return {
    passed: passedCount === checks.length,
    score: Math.round((passedCount / checks.length) * 100),
    checks,
  };
}

// ---------------------------------------------------------------------------
// Website sync checklist — manual steps before the post goes live
// ---------------------------------------------------------------------------

export const WEBSITE_SYNC_CHECKLIST: string[] = [
  "Paste the object into the posts array in src/lib/blog/posts.ts",
  "Confirm /blog/[slug] renders the post",
  "Confirm sitemap.xml includes the new slug",
  "Confirm JSON-LD (FAQ schema) appears in page source",
  "Confirm the CTA appears at the end of the post",
  "Confirm related posts show under the article",
];
