import {
  BarChart3,
  Bot,
  CalendarDays,
  CheckSquare,
  Eye,
  FileBarChart,
  FileText,
  Flower2,
  GitBranch,
  Brain,
  Rocket,
  Sprout,
  TreeDeciduous,
  Crown,
  Telescope,
  Handshake,
  Image,
  LayoutDashboard,
  MessageCircleHeart,
  MessageSquare,
  Radar,
  Server,
  Sparkles,
  Star,
  ThumbsDown,
  ThumbsUp,
  Users,
  Video,
  Workflow,
  Plug,
  Twitter,
  Zap,
} from "lucide-react";

export const navItems = [
  { href: "/", label: "PlantPal HQ", icon: LayoutDashboard },
  { href: "/automation", label: "Automation", icon: Zap },
  { href: "/calendar", label: "Content Calendar", icon: CalendarDays },
  { href: "/daily-report", label: "Daily Report", icon: FileBarChart },
  { href: "/agent-operations", label: "Agent Operations", icon: Server },
  { href: "/integrations", label: "Integrations", icon: Plug },
  { href: "/x", label: "X Dashboard", icon: Twitter },
  { href: "/collaboration", label: "Agent Collaboration", icon: GitBranch },
  { href: "/agent-brain", label: "Agent Brain (AI)", icon: Brain },
  { href: "/ivy", label: "Ivy — Chief of Staff", icon: Crown },
  { href: "/atlas", label: "Atlas — Head of Growth", icon: Telescope },
  { href: "/fern", label: "Fern — User Acquisition", icon: Sprout },
  { href: "/echo", label: "Echo — Voice of Customer", icon: MessageCircleHeart },
  { href: "/executive", label: "Executive Dashboard (Legacy)", icon: BarChart3 },
  { href: "/agents/daily-brief", label: "Ivy Executive Brief", icon: Bot },
  { href: "/agents/pipeline", label: "Content Pipeline", icon: Workflow },
  { href: "/agents/scores", label: "Content Scores", icon: Star },
  { href: "/agents/approved", label: "Approved Content", icon: ThumbsUp },
  { href: "/agents/rejected", label: "Rejected Content", icon: ThumbsDown },
  { href: "/bloom", label: "Bloom — Content Production", icon: Flower2 },
  { href: "/sage", label: "Sage — Creative Director", icon: Star },
  { href: "/sprout", label: "Sprout — Publishing", icon: Rocket },
  { href: "/content", label: "Creative Engine", icon: Sparkles },
  { href: "/social", label: "Social Posts", icon: FileText },
  { href: "/images", label: "Image Prompts", icon: Image },
  { href: "/video", label: "Video Scripts", icon: Video },
  { href: "/community", label: "Roots — Community", icon: Eye },
  { href: "/replies", label: "Social Reply Drafts", icon: MessageSquare },
  { href: "/creators", label: "Scout — Creator CRM", icon: Users },
  { href: "/oak", label: "Oak — Partnerships", icon: TreeDeciduous },
  { href: "/partnerships", label: "Partnership Tracker (Legacy)", icon: Handshake },
  { href: "/competitors", label: "Sentinel — Competitors", icon: Radar },
  { href: "/approvals", label: "Approval Queue", icon: CheckSquare },
] as const;

export const contentFormats = [
  { key: "tiktok", label: "TikTok Script" },
  { key: "reels", label: "Reels Script" },
  { key: "instagram", label: "Instagram Caption" },
  { key: "x", label: "X / Threads Post" },
  { key: "carousel", label: "Carousel Copy" },
  { key: "blog", label: "Blog Idea" },
] as const;

export const imageCategories = [
  { key: "social_graphic", label: "Social Graphics" },
  { key: "app_screenshot", label: "App Screenshots" },
  { key: "educational", label: "Educational Visuals" },
  { key: "before_after", label: "Before / After" },
] as const;

export const partnershipTypes = [
  { key: "nursery", label: "Nurseries" },
  { key: "garden_center", label: "Garden Centers" },
  { key: "landscaper", label: "Landscapers" },
  { key: "botanical_garden", label: "Botanical Gardens" },
  { key: "influencer", label: "Influencers" },
  { key: "seed_company", label: "Seed Companies" },
  { key: "home_garden_brand", label: "Home & Garden Brands" },
] as const;
