import type { ActivityItem, HQAgent } from "@/lib/hq/types";

export const HQ_AGENTS: HQAgent[] = [
  {
    id: "chief_of_staff",
    name: "Ivy",
    role: "Chief of Staff",
    station: "Executive Garden",
    status: "reviewing",
    agentState: "prioritizing",
    currentTask: "2 urgent alerts — morning brief ready with 8 scored recommendations",
    progress: 78,
    lastUpdate: "1 min ago",
    itemsCreated: 8,
    itemsNeedingReview: 2,
    accent: "#5b21b6",
    character: "ivy",
  },
  {
    id: "publishing",
    name: "Sprout",
    role: "Publishing Agent",
    station: "Schedule Desk",
    status: "waiting_for_approval",
    agentState: "waiting",
    currentTask: "2 posts awaiting schedule approval — Instagram, TikTok",
    progress: 68,
    lastUpdate: "2 min ago",
    itemsCreated: 6,
    itemsNeedingReview: 2,
    accent: "#65a30d",
    character: "sprout",
  },
  {
    id: "content",
    name: "Bloom",
    role: "Content Production Agent",
    station: "Content Garden",
    status: "writing",
    agentState: "drafting",
    currentTask: "Generating daily batch — 39 pieces from Scout, Roots, Sentinel",
    progress: 42,
    lastUpdate: "Just now",
    itemsCreated: 39,
    itemsNeedingReview: 12,
    accent: "#e85d9a",
    character: "bloom",
  },
  {
    id: "creative_director",
    name: "Sage",
    role: "Creative Director",
    station: "Review Booth",
    status: "reviewing",
    agentState: "reviewing",
    currentTask: "Reviewing 12 Bloom pieces — scoring 6 dimensions, pass threshold 80",
    progress: 81,
    lastUpdate: "4 min ago",
    itemsCreated: 8,
    itemsNeedingReview: 7,
    accent: "#0d9488",
    character: "sage",
  },
  {
    id: "community",
    name: "Roots",
    role: "Community Agent",
    station: "Listening Post",
    status: "needs_attention",
    agentState: "finding_opportunity",
    currentTask: "High-urgency Reddit thread needs reply draft",
    progress: 55,
    lastUpdate: "8 min ago",
    itemsCreated: 6,
    itemsNeedingReview: 2,
    accent: "#6b9b7a",
    character: "roots",
  },
  {
    id: "creator",
    name: "Scout",
    role: "Creator Discovery Agent",
    station: "Talent Desk",
    status: "researching",
    agentState: "searching",
    currentTask: "Qualifying creators on TikTok, YouTube, Instagram",
    progress: 33,
    lastUpdate: "12 min ago",
    itemsCreated: 4,
    itemsNeedingReview: 1,
    accent: "#c9a86c",
    character: "scout_explorer",
  },
  {
    id: "acquisition",
    name: "Fern",
    role: "User Acquisition Agent",
    station: "Growth Greenhouse",
    status: "reviewing",
    agentState: "reporting",
    currentTask: "10 opportunities scored — ~7,880 install potential. Top: Plant Rescue Challenge",
    progress: 75,
    lastUpdate: "2 min ago",
    itemsCreated: 10,
    itemsNeedingReview: 5,
    accent: "#15803d",
    character: "fern",
  },
  {
    id: "customer_voice",
    name: "Echo",
    role: "Voice of Customer Agent",
    station: "Customer Garden",
    status: "reviewing",
    agentState: "summarizing",
    currentTask: "15 feedback items analyzed — 42 users requesting Landscape Designer",
    progress: 72,
    lastUpdate: "4 min ago",
    itemsCreated: 15,
    itemsNeedingReview: 3,
    accent: "#9f1239",
    character: "echo",
  },
  {
    id: "growth",
    name: "Atlas",
    role: "Head of Growth",
    station: "Growth Observatory",
    status: "reviewing",
    agentState: "recommending",
    currentTask: "2,840 users — 5 growth recommendations scored. TikTok > X.",
    progress: 68,
    lastUpdate: "3 min ago",
    itemsCreated: 5,
    itemsNeedingReview: 3,
    accent: "#0369a1",
    character: "atlas",
  },
  {
    id: "partnerships",
    name: "Oak",
    role: "Partnership Manager",
    station: "Partnership Grove",
    status: "needs_attention",
    agentState: "outreach",
    currentTask: "1 outreach draft awaiting approval — GreenThumb Nursery negotiating",
    progress: 72,
    lastUpdate: "5 min ago",
    itemsCreated: 7,
    itemsNeedingReview: 1,
    accent: "#92400e",
    character: "oak",
  },
  {
    id: "competitor",
    name: "Sentinel",
    role: "Competitor Intelligence Agent",
    station: "Watchtower",
    status: "needs_attention",
    agentState: "alert_detected",
    currentTask: "High-severity alert: Planta Smart Water + Facebook ad campaign",
    progress: 74,
    lastUpdate: "6 min ago",
    itemsCreated: 6,
    itemsNeedingReview: 2,
    accent: "#3d4f5f",
    character: "sentinel",
  },
  {
    id: "approval",
    name: "Gate",
    role: "Approval Agent",
    station: "Launch Gate",
    status: "waiting_for_approval",
    currentTask: "5 drafts queued — awaiting human sign-off",
    progress: 100,
    lastUpdate: "1 min ago",
    itemsCreated: 0,
    itemsNeedingReview: 5,
    accent: "#2d6a4f",
    character: "gatekeeper",
  },
];

export const HQ_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    type: "approval_needed",
    title: "X post ready for review",
    summary: "Hook: Your monstera isn't dramatic. It's dehydrated.",
    timestamp: "1 min ago",
    agentId: "content",
    platform: "X",
    priority: "high",
    draft: "Your monstera isn't dramatic. It's dehydrated.\n\nThat one leaf curling like it's auditioning for a soap opera? Classic underwatering.\n\nPlantPal tracks your plant's actual thirst — not your guilt.\n\nCTA: Grow with confidence → link in bio",
    status: "pending",
  },
  {
    id: "act-2",
    type: "content_draft",
    title: "New TikTok concept",
    summary: "POV: You finally admit you have 47 plants and zero clue what half are called",
    timestamp: "3 min ago",
    agentId: "content",
    platform: "TikTok",
    priority: "medium",
  },
  {
    id: "act-3",
    type: "key_update",
    title: "Daily brief complete",
    summary: "Discovery found 16 opportunities — 12 trending topics, 4 gardener questions",
    timestamp: "5 min ago",
    agentId: "publishing",
    priority: "medium",
  },
  {
    id: "act-4",
    type: "community_opportunity",
    title: "r/gardening thread — 2.4k upvotes",
    summary: "\"What's the one gardening mistake you'll never make again?\" — 340 comments",
    timestamp: "8 min ago",
    agentId: "community",
    platform: "Reddit",
    priority: "high",
  },
  {
    id: "act-5",
    type: "comment_found",
    title: "Comment needs response",
    summary: "\"Does PlantPal work for outdoor vegetable gardens?\" on Instagram",
    timestamp: "10 min ago",
    agentId: "community",
    platform: "Instagram",
    priority: "medium",
  },
  {
    id: "act-6",
    type: "competitor_alert",
    title: "PictureThis viral TikTok",
    summary: "Plant ID challenge hit 1.2M views — angle: gamified identification",
    timestamp: "14 min ago",
    agentId: "competitor",
    priority: "medium",
  },
  {
    id: "act-7",
    type: "creator_lead",
    title: "New creator prospect",
    summary: "@gardenwithjess — 84k followers, 6.2% engagement, balcony gardening niche",
    timestamp: "18 min ago",
    agentId: "creator",
    platform: "TikTok",
    priority: "low",
  },
  {
    id: "act-8",
    type: "suggested_post",
    title: "Carousel concept scored 87",
    summary: "5 slides: \"Signs your plant is thriving vs. surviving\" — passed director review",
    timestamp: "22 min ago",
    agentId: "creative_director",
    platform: "Instagram",
    priority: "medium",
  },
  {
    id: "act-9",
    type: "approval_needed",
    title: "Reels script awaiting sign-off",
    summary: "Before/after garden transformation — emotional hook, score 84",
    timestamp: "25 min ago",
    agentId: "creative_director",
    platform: "Instagram",
    priority: "high",
    draft: "HOOK: This garden looked dead in March.\n\nSCENE 1: Wide shot, brown patches\nSCENE 2: Close-up wilted tomatoes\nSCENE 3: PlantPal care schedule on phone\nSCENE 4: July harvest montage\n\nCTA: Your comeback season starts with one reminder.",
    status: "pending",
  },
  {
    id: "act-10",
    type: "key_update",
    title: "Creative Director rejected 2 drafts",
    summary: "Generic \"5 tips\" format flagged — sent back for rewrite",
    timestamp: "30 min ago",
    agentId: "creative_director",
    priority: "low",
  },
];

export const STATUS_LABELS: Record<HQAgent["status"], string> = {
  researching: "Researching",
  writing: "Writing",
  reviewing: "Reviewing",
  waiting_for_approval: "Waiting for approval",
  approved: "Approved",
  needs_attention: "Needs attention",
  paused: "Paused",
};

export const ACTIVITY_LABELS: Record<ActivityItem["type"], string> = {
  key_update: "Key update",
  content_draft: "Content draft",
  suggested_post: "Suggested post",
  comment_found: "Comment found",
  community_opportunity: "Community opportunity",
  creator_lead: "Creator lead",
  competitor_alert: "Competitor alert",
  approval_needed: "Needs approval",
  scout_found_creator: "Creator found",
  roots_found_discussion: "Discussion found",
  suggested_partnership: "Partnership idea",
  reply_awaiting_approval: "Reply pending",
  competitor_feature: "Feature launch",
  competitor_viral: "Viral content",
  competitor_brief: "Daily brief",
  bloom_batch: "Daily batch",
  bloom_content_draft: "Content draft",
  sage_review_batch: "Sage review",
  sage_rejection: "Sage rejection",
  sage_approval: "Sage approval",
  sprout_scheduled: "Schedule pending",
  sprout_ready: "Ready to publish",
  sprout_published: "Published",
  oak_partnership: "Partnership",
  oak_outreach: "Outreach draft",
  oak_follow_up: "Follow-up",
  ivy_recommendation: "Ivy recommends",
  ivy_alert: "Ivy alert",
  ivy_brief: "Executive brief",
  ivy_daily_report: "Daily report",
  atlas_recommendation: "Growth recommendation",
  atlas_forecast: "Growth forecast",
  atlas_experiment: "Growth experiment",
  atlas_bottleneck: "Growth bottleneck",
  atlas_growth_brief: "Growth brief",
  fern_opportunity: "Acquisition opportunity",
  fern_experiment: "Acquisition experiment",
  fern_forecast: "Install forecast",
  fern_acquisition: "Acquisition scan",
  echo_feature_request: "Feature request",
  echo_sentiment: "Sentiment trend",
  echo_churn: "Churn risk",
  echo_love: "Love signal",
  echo_voc_report: "VoC report",
  echo_voc_scan: "VoC scan",
  collab_message: "Agent message",
  collab_task: "Agent task",
  collab_event: "Company event",
  collab_task_done: "Task completed",
};

export const ECHO_STATE_LABELS: Record<string, string> = {
  listening: "Listening",
  analyzing: "Analyzing",
  summarizing: "Summarizing",
  reporting: "Reporting",
  monitoring: "Monitoring",
  idle: "Idle",
};

export const FERN_STATE_LABELS: Record<string, string> = {
  analyzing: "Analyzing",
  forecasting: "Forecasting",
  testing: "Testing",
  reporting: "Reporting",
  monitoring: "Monitoring",
  idle: "Idle",
};

export const ATLAS_STATE_LABELS: Record<string, string> = {
  analyzing: "Analyzing",
  forecasting: "Forecasting",
  testing: "Testing",
  recommending: "Recommending",
  monitoring: "Monitoring",
  idle: "Idle",
};

export const IVY_STATE_LABELS: Record<string, string> = {
  reviewing: "Reviewing",
  prioritizing: "Prioritizing",
  reporting: "Reporting",
  monitoring: "Monitoring",
  idle: "Idle",
};

export const OAK_STATE_LABELS: Record<string, string> = {
  prospecting: "Prospecting",
  outreach: "Outreach",
  negotiating: "Negotiating",
  managing: "Managing",
  reporting: "Reporting",
  idle: "Idle",
};

export const SPROUT_STATE_LABELS: Record<string, string> = {
  waiting: "Waiting",
  scheduling: "Scheduling",
  ready: "Ready",
  published: "Published",
  idle: "Idle",
};

export const SAGE_STATE_LABELS: Record<string, string> = {
  reviewing: "Reviewing",
  scoring: "Scoring",
  rejecting: "Rejecting",
  approving: "Approving",
  reporting: "Reporting",
  idle: "Idle",
};

export const BLOOM_STATE_LABELS: Record<string, string> = {
  sourcing: "Sourcing Inputs",
  drafting: "Drafting",
  queueing: "Queueing",
  reporting: "Reporting",
  idle: "Idle",
};

export const SENTINEL_STATE_LABELS: Record<string, string> = {
  monitoring: "Monitoring",
  analyzing: "Analyzing",
  alert_detected: "Alert Detected",
  reporting: "Reporting",
  idle: "Idle",
};

export const SCOUT_STATE_LABELS: Record<string, string> = {
  searching: "Searching",
  analyzing: "Analyzing",
  scoring: "Scoring",
  found_match: "Found Match",
  idle: "Idle",
};

export const ROOTS_STATE_LABELS: Record<string, string> = {
  listening: "Listening",
  monitoring: "Monitoring",
  finding_opportunity: "Finding Opportunity",
  drafting_reply: "Drafting Reply",
  awaiting_approval: "Awaiting Approval",
};
