-- PlantPal Marketing OS — Phase 11 seed: Oak partnership pipeline
-- Run AFTER 015_oak_partnership_manager.sql

INSERT INTO public.oak_partnership_pipeline (
  id, creator_lead_id, partner_name, partner_type, contact_name, contact_email, location,
  stage, outreach_draft, collaboration_idea, follow_up_at, follow_up_note,
  revenue_generated, installs_generated, priority, notes, outreach_approved
) VALUES
  ('o1000000-0000-4000-8000-000000000001', NULL, 'GreenThumb Nursery Co.', 'nursery',
   'Maria Chen', 'partnerships@greenthumb.example', 'Portland, OR',
   'negotiating',
   'Hi Maria — PlantPal helps your customers keep plants alive after they leave your nursery. We''d love to co-branded care cards for top sellers.',
   'In-store QR → PlantPal care plan for every plant sold. Track installs from nursery referrals.',
   NOW() + INTERVAL '2 days', 'Send revised co-marketing deck before Thursday call',
   2400.00, 186, 'high', 'Strong local presence — 12k monthly foot traffic', TRUE),
  ('o1000000-0000-4000-8000-000000000002', NULL, '@UrbanJungleJen', 'influencer',
   'Jen Martinez', 'jen@urbanjungle.blog', 'Austin, TX',
   'replied',
   'Hey Jen — loved your monstera rehab series. PlantPal could power the ''30-day rescue'' challenge your audience keeps asking for.',
   'Plant Rescue Challenge: Jen documents 5 saves using PlantPal reminders — affiliate link + unique code.',
   NOW() + INTERVAL '1 day', 'Follow up on rate card — she replied interested in Q3',
   0, 0, 'high', 'Replied via email — wants audience fit data', TRUE),
  ('o1000000-0000-4000-8000-000000000003', NULL, 'Botanical Garden of the Rockies', 'botanical_garden',
   'Dr. Sam Okonkwo', 'education@bgr.example', 'Denver, CO',
   'active',
   'Dr. Okonkwo — PlantPal would love to sponsor your beginner houseplant workshops with digital care companions for attendees.',
   'Workshop bundle: printed care guide + PlantPal onboarding for 200 attendees per session.',
   NOW() + INTERVAL '14 days', 'Quarterly impact review — installs + workshop NPS',
   5200.00, 412, 'normal', 'Active since March — 2 workshops completed', TRUE),
  ('o1000000-0000-4000-8000-000000000004', NULL, 'Stone & Stem Landscapers', 'landscaper',
   'Tyler Brooks', 'tyler@stoneandstem.example', 'Charlotte, NC',
   'contacted',
   'Tyler — your transformation reels are exactly what new homeowners search for. PlantPal helps clients maintain what you install.',
   'Post-install care handoff: landscaper sets up PlantPal for each client — referral fee per activated account.',
   NOW() + INTERVAL '5 days', 'Initial outreach sent — await reply',
   0, 0, 'normal', 'Cold outreach — saw on Instagram', FALSE),
  ('o1000000-0000-4000-8000-000000000005', NULL, 'Bloom & Co. Home Garden Brand', 'brand',
   'Rachel Kim', 'rachel@bloomandco.example', 'Remote / US',
   'negotiating',
   'Rachel — co-launch a ''first apartment plant kit'' with PlantPal as the care layer. Your design, our retention.',
   'Limited edition kit + 90-day PlantPal trial — track bundle installs and repeat purchase lift.',
   NOW() + INTERVAL '3 days', 'Legal reviewing co-brand terms',
   1800.00, 94, 'high', 'Brand wants exclusivity in apartment segment', TRUE),
  ('o1000000-0000-4000-8000-000000000006', NULL, 'Sunrise Garden Center', 'garden_center',
   'Pat O''Brien', 'pat@sunrisegarden.example', 'Columbus, OH',
   'completed',
   'Pat — thanks for the spring planting partnership. Ready to plan fall bulb season?',
   'Fall bulb workshop + PlantPal bulb planting reminders — repeat last year''s format.',
   NULL, 'Partnership completed — archive Q2, plan Q4 renewal',
   3100.00, 267, 'normal', 'Completed spring campaign — strong ROI', TRUE),
  ('o1000000-0000-4000-8000-000000000007', NULL, '@PlantDadMike', 'influencer',
   'Mike Torres', 'mike@plantdadmedia.example', 'Miami, FL',
   'active',
   'Mike — your beginner content aligns perfectly with PlantPal''s onboarding. Let''s extend the summer collab.',
   'Monthly ''Plant Dad Check-in'' live stream with PlantPal care streak leaderboard.',
   NOW() + INTERVAL '7 days', 'Mid-campaign metrics review',
   8900.00, 1204, 'high', 'Top performing influencer partner YTD', TRUE);

INSERT INTO public.agent_activity_log (agent_id, action, detail, metadata) VALUES
  ('oak', 'pipeline_review', '7 partnerships in pipeline — 2 negotiating, 2 active, 1 completed', '{"total":7}'),
  ('oak', 'outreach_drafted', 'Outreach draft queued for Stone & Stem Landscapers — awaiting approval', '{"partner":"landscaper"}'),
  ('oak', 'follow_up', '3 follow-up reminders due this week', '{"due":3}'),
  ('oak', 'metrics', 'Partnership revenue $21,400 · 2,163 installs attributed', '{"revenue":21400,"installs":2163}');
